# Generated by Django 3.2.9 on 2021-12-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_results_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='all_questions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='results',
            name='false_ans',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='results',
            name='true_ans',
            field=models.IntegerField(),
        ),
    ]
