# Generated by Django 3.2.9 on 2021-12-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20211202_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='category',
        ),
        migrations.RemoveField(
            model_name='results',
            name='test',
        ),
        migrations.AddField(
            model_name='results',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lessons'),
        ),
        migrations.RemoveField(
            model_name='results',
            name='username',
        ),
        migrations.AddField(
            model_name='results',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lessons.users'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.category')),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='subcategory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lessons.subcategory'),
            preserve_default=False,
        ),
    ]
